export const categories = [
  {
    id: 1,
    name: "Stores",
    icon: "UtensilsCrossed",
    color: "#FF6B35",
  },
  {
    id: 2,
    name: "Groceries",
    icon: "ShoppingCart",
    color: "#10B981",
  },
  {
    id: 3,
    name: "Market",
    icon: "Store",
    color: "#6366F1",
  },
  {
    id: 4,
    name: "Health & Wellness",
    icon: "Heart",
    color: "#EC4899",
  },
  {
    id: 5,
    name: "Beauty & Care",
    icon: "Sparkles",
    color: "#F59E0B",
  },
  {
    id: 6,
    name: "Pharmacy",
    icon: "Pill",
    color: "#14B8A6",
  },
  {
    id: 7,
    name: "Pet Supplies",
    icon: "PawPrint",
    color: "#8B5CF6",
  },
  {
    id: 8,
    name: "Electronics",
    icon: "Smartphone",
    color: "#3B82F6",
  },
  {
    id: 9,
    name: "Books & Stationery",
    icon: "BookOpen",
    color: "#78716C",
  },
  {
    id: 10,
    name: "Flowers & Gifts",
    icon: "Gift",
    color: "#F43F5E",
  },
  {
    id: 11,
    name: "Sports & Fitness",
    icon: "Dumbbell",
    color: "#EF4444",
  },
  {
    id: 12,
    name: "Home & Garden",
    icon: "Home",
    color: "#059669",
  },
  {
    id: 13,
    name: "Toys & Games",
    icon: "Gamepad2",
    color: "#7C3AED",
  },
  {
    id: 14,
    name: "Automotive",
    icon: "Car",
    color: "#475569",
  },
  {
    id: 15,
    name: "Fashion",
    icon: "Shirt",
    color: "#DB2777",
  },
  {
    id: 16,
    name: "Cafe & Bakery",
    icon: "Coffee",
    color: "#92400E",
  },
  {
    id: 17,
    name: "Bakery",
    icon: "Croissant",
    color: "#D97706",
  },
  {
    id: 18,
    name: "Alcohol",
    icon: "Wine",
    color: "#9333EA",
  },
  {
    id: 19,
    name: "Baby Care",
    icon: "Baby",
    color: "#06B6D4",
  },
  {
    id: 20,
    name: "Organic",
    icon: "Leaf",
    color: "#22C55E",
  },
];
